### ISSUE TITLE
Paladin WA - Right icons misalignment after adjusting Icon Width and height

### ISSUE THREAD

**Issue by ShotaroKaneda** [Rakizi/NAG-issues#10]
Fresah profile (reset), Fresh WA import.
Latest published versions of NAG and Paladin WA

Change icon height and width in NAG will lead to misaligned right side icons as can be seen in the attached screenshot.
![image](https://github.com/user-attachments/assets/fe9f16ba-d6de-46df-9c8d-43347b848a7f)

**Comment by Rakizi** [comment]
unfortunately, the WA added stuff doesn't have the best integration as the addon stuff.  Will be eventully makingg those trackers internal like priest is using.

**Comment by Rakizi** [comment]
width/height should not have been set that way. scaling added to whole addon frame which allows for this.
