### ISSUE TITLE
floating 5 and  " " in dk weakaura

### ISSUE THREAD

**Issue by Rakizi** [Rakizi/NAG-issues#49]
![image](https://github.com/user-attachments/assets/f51e46fc-95b9-4197-a2fa-c06f6283c3df)

**Comment by adamthemute** [comment]
Got the same issue, showed up today. Followed the whole delete/reinstall thing.
![WoWScrnShot_111224_035244](https://github.com/user-attachments/assets/ede2d294-abc9-465c-8425-e9fde4e66ed4)

**Comment by Rakizi** [comment]
fonsas fix
