### ISSUE TITLE
[SOD] Spec options dont show anything even though there are rotations in the paladin.lua file

### ISSUE THREAD

**Issue by afonsohfontes** [Rakizi/NAG-issues#74]
https://cdn.discordapp.com/attachments/1140048977107099740/1308190442331963564/image.png?ex=673d0aca&is=673bb94a&hm=4fa5084d96b92c4c0174d1573ee5b35bc23e2e08a7843ea2bc524186b5756d8f&

Spec options dont show anything even though there are rotations in the paladin.lua file

**Comment by Rakizi** [comment]
this should be fixed, the copyprofile wasn't copying right
